config/routes.rb
SugarOnRailsBasic::Application.routes.draw do
  match ':module' => 'sugar_beans#list', :as => "module"
  match ':module/:id' => 'sugar_beans#show', :as => "sugar_bean"
  match ':module/:id/:association' => 'sugar_beans#show_associations', :as => "sugar_bean_associations"
  root :to => "sugar_beans#list", :module => "accounts"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sugar_beans_controller.rb
class SugarBeansController < ApplicationController
  # This controller provides a generic interface to SugarCRM.  It expects
  # a module name to be passed as an argument
  def list
    @sugar_module = params[:module]
    begin
      @beans = class_for(params[:module]).all(:limit => 10)
    rescue NameError
      @sugar_modules = available_modules.sort
      render :action => "available_modules"
    end
  end
  
  def show
    @sugar_module = params[:module]
    @bean         = class_for(params[:module]).find(params[:id])
  end
  
  def show_associations
    @sugar_module = params[:module]
    @bean         = class_for(params[:module]).find(params[:id])
    @association  = params[:association]
    @beans        = @bean.send(@association.to_sym)
  end
  
  private 
  
  def available_modules
    ["SugarCRM", SugarCRM.namespace].join("::").constantize.constants
  end

  def class_for(mod)
    ["SugarCRM", SugarCRM.namespace, mod.classify].join("::").constantize
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def module_menu
    html = ""
    ["Accounts", "Opportunities", "Users"].each do |m|
      html << content_tag(:li, :class => :module) do 
        link_to(m, module_path(m.downcase))
      end
    end
    html
  end
end

app/helpers/sugar_beans_helper.rb
module SugarBeansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SugarOnRailsBasic</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div class="header">
    <ul class="modules">
      <%= raw module_menu %>
    </ul>
  </div>

<%= yield %>

</body>
</html>

app/views/sugar_beans/_associations.html.erb
<div id="associations">
  <h2>Associations</h2>
  <table>
    <%- @bean.associations.each do |a| %>
    <tr>
      <td><%= link_to(a.proxy_methods[0], sugar_bean_associations_path(@sugar_module, @bean.id, a.proxy_methods[0]))  %></td>
    </tr>
    <%- end %>
  </table>
</div>

app/views/sugar_beans/_attributes.html.erb
<div id="attributes">
  <h2>Attributes</h2>
  <table>
    <%- @bean.attributes.sort.each do |a| %>
    <tr>
      <th><%= a[0] %>:</th>
      <td><%= a[1] %></td>
    </tr>
    <%- end %>
  </table>
</div>

app/views/sugar_beans/_beans.html.erb
<%- if @beans.length > 0 %>
<table class="beans">
  <%- @beans.each do |bean| %>
  <tr id="<%= bean.id %>">
    <td><%= link_to(bean.name, sugar_bean_path(bean.class._module.name.downcase, bean.id)) %></td>
  </tr>
  <%- end %>
</table>
<%- else %>
<p class="beans">No records found!</p>
<%- end %>

app/views/sugar_beans/available_modules.html.erb
<h1>Invalid Module: <%= @sugar_module %></h1>

<div id="available_modules">
  <h2>Available modules:</h2>
  <ul>
    <%- @sugar_modules.each do |m| %>
    <% if m.respond_to? :tableize %><li class="module"><%= m.tableize %></li><% end %>
    <%- end %>
  </ul>
</div>

app/views/sugar_beans/list.html.erb
<div class="container">
  <div class="container_header"><%= @module.capitalize %></div>
  <table class="beans">
    <%- @beans.each do |bean| %>
    <tr id="<%= bean.id %>">
      <td><%= link_to(bean.name, sugar_bean_path(@module, bean.id)) %></td>
    </tr>
    <%- end %>
  </table>
</div>

app/views/sugar_beans/show.html.erb
<div class="container">
  <div class="container_header">Details</div>
  <div class="container_content">  
    <div class="bean">
      <div id="tabs">
      	<ul>
      		<li><a href="#attributes">Attributes</a></li>
      		<li><a href="#associations">Associations</a></li>
        </ul>
      </div>
      <%= render :partial => "attributes" %>
      <%= render :partial => "associations" %>
    </div>
  </div>
</div>

<script>
	$(function() {
		$("#tabs").tabs();
	});
</script>

app/views/sugar_beans/show_associations.html.erb
<div class="container">
  <div class="container_header"><%= @sugar_module.capitalize + ": " + @association.capitalize %></div>
  <div class="container_content">  
    <%= render :partial => "beans" %>
  </div>
</div>